### ISSUE TITLE
Classes and elements not defined when creating custom node

### ISSUE THREAD

**Issue by deplanty** [leon-thomm/Ryven#120]
I am following the "Quick start" tutorial and I have an unexpected error in the "Defining node" section.

Here is simplified version of the tutorial with the error :

```python
from ryven.NENV import *

class PrintNode(Node):
    title = 'Print'
    init_inputs = [
        NodeInputBP(),
    ]

    def update_event(self, inp=-1):
        print(self.input(0))
```

I have the following error :
```
Traceback (most recent call last):
  File "c:/Users/xyz/.ryven/packages/xyz/nodes.py", line 4, in <module>
    class PrintNode(Node):
  File "c:/Users/xyz/.ryven/packages/xyz/nodes.py", line 7, in PrintNode
    NodeInputBP(),
TypeError: 'NoneType' object is not callable
```

Also, I have the same error with the `RandNode` and `dtypes` :

```
    NodeInputBP(dtype=dtypes.Data(default=1))
AttributeError: 'NoneType' object has no attribute 'Data'
```

I am working with Python 3.7.5 on Windows 10 64 bit.

PS : Great project !

**Comment by leon-thomm** [comment]
yes, glad you resolved it!
